[package]
name = "crypto-testing"
version = "0.1.0"
authors = ["nescoto"]
edition = "2018"

[dependencies]
ferris-says = "0.1"
secp256k1 = {version="0.11.4", features=["rand"]}
rand = "0.3"
hex = "0.3.2"
sha2 = "0.8.0"